# Generated by Django 3.1.1 on 2020-11-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20201129_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
