# Generated by Django 3.1.1 on 2020-11-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_auto_20201129_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=200)),
                ('contact', models.BigIntegerField()),
                ('address', models.CharField(max_length=300)),
                ('timing', models.IntegerField()),
            ],
        ),
    ]
