# Generated by Django 3.1.1 on 2020-11-30 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0007_auto_20201130_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='front.doctor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='timing',
            field=models.CharField(max_length=20),
        ),
    ]
