# Generated by Django 3.1.1 on 2020-11-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0011_auto_20201130_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doc_name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
