# Generated by Django 3.1.1 on 2020-11-30 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0012_auto_20201130_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='doc_name',
        ),
    ]
