# Generated by Django 3.1.1 on 2020-11-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0014_patient_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doc',
            field=models.CharField(max_length=200),
        ),
    ]
